### PR TITLE
Create update_dblp_auto.py

### PR DESCRIPTION
**Pull request by lancercat**
Make things lazier by adding a semiauto updater:
It only needs manul intervention when there is more than one choices that are not from arxiv,

### CODE REVIEW

**Comment by lancercat** [comment]
4sec is still too short and still triggers 429 I will find the value by trial and error.

**Comment by volkm** [comment]
Thanks, I very much like this idea!
It seems to me that the code is very similar to `update_from_dblp.py`. Would it possible to integrate your changes into the existing file and maybe add a cmdline flag `--disable-auto` to disable the automatic selection? I imagine that for most users, this automatic selection is preferred and we should make it the default.

**Comment by lancercat** [comment]
Done adding an option, not tested the manual mode yet as I am crawling to fix my 300+ citation entries... 
Well, my suggestion is we keep both, and we merge them when the new code looks robust enough.

**Comment by volkm** [comment]
I integrated your suggestions into `update_from_dblp` and enabled the automatic selection by default. It can be disabled with `--disable-auto`. Additional cmdline flags are `--include-arxiv` to explicitly keep arXiv entries in the search results and `--sleep-time` to set the waiting time between requests (in order to prevent too many requests).

**Pull request merged**
